# Stage 1: Build the application
FROM openjdk:22 AS BUILD
WORKDIR /app
COPY backend /app
RUN mvn clean package -DskipTests

# Stage 2: Run the application
FROM openjdk:22
COPY --from=BUILD /app/target/backend-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
LABEL authors="nguye"
